services:
  web:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - labs-gems:/usr/local/bundle
    command: bash -c "bundle install && bundle exec ruby runner.rb && ruby server.rb"
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "4000:3000"
    depends_on:
      - db
      - redis
      - worker
    networks:
      - rebase-labs
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '87273836'
    volumes:
      - ./database:/var/lib/postgresql
    networks:
      - rebase-labs
  test:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - labs-gems:/usr/local/bundle
    environment:
      - REDIS_URL=redis://redis:6397
      - RACK_ENV=test
    command: bash -c "bundle install && bundle exec ruby runner_db.rb && bundle exec rspec"
    depends_on:
      - test-db
      - redis
      - worker
    networks:
      - rebase-labs
  test-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: '87273836'
    networks:
      rebase-labs:
        aliases:
          - db
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - rebase-labs
  worker:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - labs-gems:/usr/local/bundle
    command: bash -c "bundle install && sidekiq -r ./exams_importer.rb"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - rebase-labs

volumes:
  labs-gems:

networks:
  rebase-labs: